-- STAGE 20: DATABASE CLEANUP
-- WARNING: DO NOT RUN THIS UNTIL YOU HAVE VERIFIED ALL IMAGES WERE SUCCESSFULLY MIGRATED TO THE product_images TABLE.
-- ONCE THIS IS RUN, THE OLD IMAGE ARRAY DATA IS PERMANENTLY DELETED.

ALTER TABLE products DROP COLUMN IF EXISTS product_images;
